version: '2'
services:
    streamer-app:
        image: streamer
        external_links:
            - streamer-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/streamer?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    streamer-mysql:
        extends:
            file: mysql.yml
            service: streamer-mysql
